[package]
name = "ssw"
version = "0.1.0"
authors = ["Adam Perry <adam.n.perry@gmail.com>"]
build = "build.rs"

[dependencies]
libc = "0.2"

[build-dependencies]
cc = "1.0"

[dev-dependencies]
arbitrary_dna = { path = "../arbitrary_dna" }
bio = { path = "../vendor/rust-bio" }
quickcheck = "0.3"
